### ISSUE TITLE
Purpose of CRTP in System class

### ISSUE THREAD

**Issue by FireFlyForLife** [VIGameStudio/Concordia#6]
Why does the [System ](https://github.com/VIGameStudio/Concordia/blob/master/src/Concordia/SystemMgr.hpp)class need to have the template of the derrived system type? We can generate the id from a free function. And I also cannot think of a reason for giving an id to a system.

**Comment by Belfer** [comment]
The ID registration for the systems is used to remove a system if it's no longer needed. It can also be used to associate an entity with a system. The pattern here is the same for components. Can you elaborate on generating the ID from a free function?

**Comment by FireFlyForLife** [comment]
I meant [generating an ID in a free function like I did in my fork](https://github.com/FireFlyForLife/Concordia/blob/master/src/Concordia/Identification.hpp#L11).

I see that the ID has its uses.

**Comment by Belfer** [comment]
I think it would be best to leave the ID registration by inheritance, for now, this may change in the future.
